### ISSUE TITLE
error

### ISSUE THREAD

**Issue by r0x5r** [medbsq/ssrf#1]
urls_path=at.txt    colab=3          threads=c9pdqhp2vtc0000bf3aggr5g5aayyyyyb.interact.sh  cookies=None 
Traceback (most recent call last):
  File "/home/kali/tool/ssrf/ssrf_fuzz.py", line 179, in <module>
    Main()
  File "/home/kali/tool/ssrf/ssrf_fuzz.py", line 174, in Main
    pool(filename, threads, colab, cookies)
  File "/home/kali/tool/ssrf/ssrf_fuzz.py", line 130, in pool
    with ThreadPoolExecutor(max_workers=threads) as executor:
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 137, in __init__
    if max_workers <= 0:
TypeError: '<=' not supported between instances of 'str' and 'int'

**Comment by medbsq** [comment]
@rohit0x5 problem solved.
can you confirm !!!

**Comment by r0x5r** [comment]
now may be this not work new error is 
i use paramspider url 
[ done ] http://example.com/index.php?url=FUZZ
why this if i use collabrator then remove fuzz to collabrator

**Comment by medbsq** [comment]
@rohit0x5 can you explain more ???
